package interviewEx;

//Write a method that returns the sum of all even Fibonacci numbers. Consider all Fibonacci numbers that are less than or equal to n.
//    Each new element in the Fibonacci sequence is generated by adding the previous two elements.
//    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

public class EvenFiboSum {

    public Integer evenFibonacciSum(Integer n) {
        int next = 0;
        int previous = 0;
        int current = 1;
        int sum = 0;

        if (n == 1) {return 1;}
        do {
            next = previous + current;
            previous = current;
            current = next;
            if (next % 2 == 0 && next <= n) {
                sum += next;
            }
        } while (next <= n);

//        for (int i = 0; next <= n; i++) {
//            next = previous + current;
//            previous = current;
////            System.out.println(previous + " ");
//            current = next;
//            if (next % 2 == 0 && next <= n) {
//                sum += next;
////                System.out.println("even next " + next + " ");
//            }
//        }
        return sum;
    }

    public static void main(String[] args) {
        System.out.println("evenFibonacciSum: " + new EvenFiboSum().evenFibonacciSum(450));
    }
}


